### ISSUE TITLE
Strange Behavior in Photoshop

### ISSUE THREAD

**Issue by clarkewd** [oin/Clicker#1]
Jonathan - Thanks for creating Clicker - great solution / workaround for the lack of mouse support in Karabiner-Elements. Seems to work great in all applications - except Photoshop. Currently using CS6.

The behavior is pretty hard to describe, it's almost as if the button on the mouse were to get "stuck down" and it is waiting for me to press the key again to release. It does something - like completing a line - but then appears to become "stuck down" again. Not sure if this makes sense - I've been trying to figure out what exactly it is doing and how to explain it better for a few days now.

Let me know if you have any insight.

**Comment by oin** [comment]
Thanks!

Maybe Photoshop handles events a bit differently…

I don't have Photoshop CS6 handy, so I can't really try this behavior (a quick test on another computer shows it seems to work with Photoshop CC 2017).

It could be worth:

- having a look at the disassembled code to see how Photoshop handles mouse input (e.g., with apps like [Hopper](https://www.hopperapp.com), but not really fun to do)
- trying Photoshop CS6 on a computer where Karabiner works and see if it behaves in the same way
- looking for other apps that exhibit the same behavior

Maybe you could write down the exact actions you're doing in terms of input events (mouse down, move, up…) so that we're clear on what is processed.

**Comment by clarkewd** [comment]
Thanks for the quick response. Karabiner ( the full version ) used to work fine when used with OSX 10.11 and CS6. I do have Hopper - but agree - might be better to try other things first. Haven't seen this behavior in any other app - Clicker works pretty seamlessly in the rest.

Reading through the code in `ClickerController.m` and trying to wrap my head around the code there. Feels like there might need to be some of periodic check to make sure the key is still actually pressed down and cancel the drag event if it is not.

**Comment by oin** [comment]
[This bit](https://github.com/oin/Clicker/blob/master/Clicker/ClickerController.m#L35) of code triggers mouse event outputs. It is executed whenever the key with the proper key code has been pressed or released.

In theory, the only way it'd fail to see a key press or release event is if there was another HID event tap created after this one (e.g., when Photoshop starts), and inserted at the head of the tap queue, that would steal the key release (`kCGEventKeyUp`) events we're interested in.

AFAIK, you can't just poll the state of the keyboard, so you can't really say _"let's see whether this key is still pressed"_ every 100ms or so.

**Comment by clarkewd** [comment]
Would it be worth looking at how Karabiner used to handle mouse events and seeing if that is any different - maybe [somewhere around here](https://github.com/tekezo/Karabiner/blob/05ca98733f3e3501e0679814c3795d1cb57e177f/src/util/EventViewer/Classes/EventQueue.m#L311)?

**Comment by clarkewd** [comment]
Looks like with newer version of photoshop it works ok
